// Package bls provides the Bundeslebensmittelschlüssel 4.0 as a foodimport
// source. The data is a slim CSV generated by scripts/bls-to-csv.py and
// embedded, so importing needs no network.
//
// Source: Max Rubner-Institut (2025): Bundeslebensmittelschlüssel (BLS),
// Version 4.0 – Deutsche Nährstoffdatenbank. Karlsruhe.
// DOI: 10.25826/Data20251217-134202-0. License: CC BY 4.0.
package bls

import (
	"bytes"
	_ "embed"
	"encoding/csv"
	"fmt"
	"io"
	"strconv"
	"strings"

	"schautrack/internal/foodimport"
)

//go:embed bls_4_0.csv
var data []byte

// Source is the embedded BLS 4.0 data.
type Source struct{}

func (Source) Name() string { return "bls" }

func (Source) Foods() ([]foodimport.Food, error) {
	return Parse(bytes.NewReader(data))
}

var header = []string{"code", "name", "classification", "kcal", "protein", "carbs", "fat", "fiber", "sugar"}

// Parse reads the CSV written by scripts/bls-to-csv.py. An empty cell is
// unknown (nil), not 0.
func Parse(r io.Reader) ([]foodimport.Food, error) {
	cr := csv.NewReader(r)
	got, err := cr.Read()
	if err != nil {
		return nil, fmt.Errorf("read header: %w", err)
	}
	if strings.Join(got, ",") != strings.Join(header, ",") {
		return nil, fmt.Errorf("unexpected header %v, want %v", got, header)
	}

	var foods []foodimport.Food
	seen := map[string]bool{}
	for {
		rec, err := cr.Read()
		if err == io.EOF {
			return foods, nil
		}
		if err != nil {
			return nil, err
		}
		if seen[rec[0]] {
			return nil, fmt.Errorf("duplicate code %q", rec[0])
		}
		seen[rec[0]] = true

		f := foodimport.Food{Code: rec[0], Name: rec[1], Classification: rec[2]}
		for i, dst := range []**float64{&f.Kcal, &f.Protein, &f.Carbs, &f.Fat, &f.Fiber, &f.Sugar} {
			cell := strings.TrimSpace(rec[3+i])
			if cell == "" {
				continue
			}
			v, err := strconv.ParseFloat(cell, 64)
			if err != nil {
				return nil, fmt.Errorf("code %s, column %s: %w", rec[0], header[3+i], err)
			}
			*dst = &v
		}
		foods = append(foods, f)
	}
}
